services:
    # Form field types
    
    rk_download_module.form.type.field.multilist:
        class: RK\DownLoadModule\Form\Type\Field\MultiListType
        arguments:
            - "@rk_download_module.listentries_helper"
        tags:
            - { name: form.type }
