services:
    # Form field types
    
    rk_download_module.form.type.field.multilist:
        class: RK\DownLoadModule\Form\Type\Field\MultiListType
        arguments:
            - "@rk_download_module.listentries_helper"
        tags: ['form.type']
    
    rk_download_module.form.type.field.upload:
        class: RK\DownLoadModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@rk_download_module.image_helper"
            - "@rk_download_module.upload_helper"
        tags: ['form.type']
