services:
    # Helper services
    rk_download_module.archive_helper:
        class: RK\DownLoadModule\Helper\ArchiveHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@rk_download_module.entity_factory"
            - "@rk_download_module.permission_helper"
            - "@rk_download_module.workflow_helper"
            - "@rk_download_module.hook_helper"
    
    rk_download_module.category_helper:
        class: RK\DownLoadModule\Helper\CategoryHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_categories_module.category_registry_repository"
            - "@zikula_categories_module.api.category_permission"
    
    rk_download_module.collection_filter_helper:
        class: RK\DownLoadModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@rk_download_module.permission_helper"
            - "@zikula_users_module.current_user"
            - "@rk_download_module.category_helper"
            - "@zikula_extensions_module.api.variable"
            - "@=service('zikula_extensions_module.api.variable').get('RKDownLoadModule', 'showOnlyOwnEntries', false)"
    
    rk_download_module.controller_helper:
        class: RK\DownLoadModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_download_module.archive_helper"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@rk_download_module.entity_factory"
            - "@rk_download_module.collection_filter_helper"
            - "@rk_download_module.permission_helper"
            - "@rk_download_module.model_helper"
            - "@rk_download_module.image_helper"
            - "@rk_download_module.feature_activation_helper"
    
    rk_download_module.entity_display_helper:
        class: RK\DownLoadModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_download_module.listentries_helper"
    
    rk_download_module.feature_activation_helper:
        class: RK\DownLoadModule\Helper\FeatureActivationHelper
    
    rk_download_module.hook_helper:
        class: RK\DownLoadModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    rk_download_module.image_helper:
        class: RK\DownLoadModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    rk_download_module.listentries_helper:
        class: RK\DownLoadModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    rk_download_module.model_helper:
        class: RK\DownLoadModule\Helper\ModelHelper
        arguments:
            - "@rk_download_module.entity_factory"
    
    rk_download_module.permission_helper:
        class: RK\DownLoadModule\Helper\PermissionHelper
        arguments:
            - "@service_container"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@zikula_users_module.user_repository"
    
    rk_download_module.search_helper:
        class: RK\DownLoadModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@request_stack"
            - "@rk_download_module.entity_factory"
            - "@rk_download_module.controller_helper"
            - "@rk_download_module.entity_display_helper"
            - "@rk_download_module.permission_helper"
            - "@rk_download_module.feature_activation_helper"
            - "@rk_download_module.category_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: RKDownLoadModule }
    
    rk_download_module.upload_helper:
        class: RK\DownLoadModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@filesystem"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('RKDownLoadModule')"
            - "%datadir%"
    
    rk_download_module.view_helper:
        class: RK\DownLoadModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.internal.theme_filter"
            - "@rk_download_module.controller_helper"
            - "@rk_download_module.permission_helper"
    
    rk_download_module.workflow_helper:
        class: RK\DownLoadModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@rk_download_module.entity_factory"
            - "@rk_download_module.listentries_helper"
            - "@rk_download_module.permission_helper"
