<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Form\Type;

use RK\DownLoadModule\Form\Type\Base\AbstractFileType;

/**
 * File editing form type implementation class.
 */
class FileType extends AbstractFileType
{
    // feel free to extend the file editing form type class here
}
