<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule;

use RK\DownLoadModule\Base\AbstractDownLoadEvents;

/**
 * Events definition implementation class.
 */
class DownLoadEvents extends AbstractDownLoadEvents
{
    // feel free to extend the events definition here
}
