<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\ContentType\Form\Type;

use RK\DownLoadModule\ContentType\Form\Type\Base\AbstractItemType;

/**
 * Detail content type form type implementation class.
 */
class ItemType extends AbstractItemType
{
    // feel free to extend the detail content type form type class here
}
