<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Block;

use RK\DownLoadModule\Block\Base\AbstractItemBlock;

/**
 * Generic item detail block implementation class.
 */
class ItemBlock extends AbstractItemBlock
{
    // feel free to extend the item detail block here
}
