<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Event;

use RK\DownLoadModule\Event\Base\AbstractConfigureItemActionsMenuEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ConfigureItemActionsMenuEvent extends AbstractConfigureItemActionsMenuEvent
{
    // feel free to extend the event class here
}
