<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Listener;

use RK\DownLoadModule\Listener\Base\AbstractModuleDispatchListener;

/**
 * Event handler implementation class for dispatching modules.
 */
class ModuleDispatchListener extends AbstractModuleDispatchListener
{
    // feel free to enhance the parent methods
}
