<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Listener;

use RK\DownLoadModule\Listener\Base\AbstractUserRegistrationListener;

/**
 * Event handler implementation class for user registration events.
 */
class UserRegistrationListener extends AbstractUserRegistrationListener
{
    // feel free to enhance the parent methods
}
