<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Entity;

use RK\DownLoadModule\Entity\Base\AbstractFileCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing file categories.
 *
 * This is the concrete category class for file entities.
 * @ORM\Entity(repositoryClass="\RK\DownLoadModule\Entity\Repository\FileCategoryRepository")
 * @ORM\Table(name="rk_downlo_file_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class FileCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
