<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\ContentType;

use RK\DownLoadModule\ContentType\Base\AbstractItemListType;

/**
 * Generic item list content type implementation class.
 */
class ItemListType extends AbstractItemListType
{
    // feel free to extend the content type here
}
