<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\DependencyInjection;

use RK\DownLoadModule\DependencyInjection\Base\AbstractRKDownLoadExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKDownLoadExtension extends AbstractRKDownLoadExtension
{
    // custom enhancements can go here
}
