<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\HookSubscriber;

use RK\DownLoadModule\HookSubscriber\Base\AbstractFileFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class FileFilterHooksSubscriber extends AbstractFileFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
