<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Form\DataTransformer;

use RK\DownLoadModule\Form\DataTransformer\Base\AbstractListFieldTransformer;

/**
 * List field transformer implementation class.
 *
 * This data transformer treats multi-valued list fields.
 */
class ListFieldTransformer extends AbstractListFieldTransformer
{
    // feel free to add your customisation here
}
