<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\HookSubscriber;

use RK\DownLoadModule\HookSubscriber\Base\AbstractFileFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class FileFormAwareHookSubscriber extends AbstractFileFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
