<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownLoadModule\Entity\Factory\Base;

use RK\DownLoadModule\Entity\FileEntity;
use RK\DownLoadModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    /**
     * Initialises a given file instance.
     *
     * @param FileEntity $entity The newly created entity instance
     *
     * @return FileEntity The updated entity instance
     */
    public function initFile(FileEntity $entity)
    {
        $entity->setEndDate(new \DateTime('2099-12-31'));
        return $entity;
    }

}
